# Generated by Django 4.2.13 on 2026-08-10 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('customers', '0001_initial'),
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_date', models.DateTimeField()),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BKASH', 'bKash'), ('NAGAD', 'Nagad'), ('BANK_TRANSFER', 'Bank Transfer'), ('CARD', 'Card'), ('OTHER', 'Other')], default='CASH', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='businesses.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('credit_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='credit.creditsale')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='payments.payment')),
            ],
        ),
    ]
