# Generated by Django 4.2.13 on 2026-08-10 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReliabilityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('on_time_payment_component', models.IntegerField(default=0)),
                ('consistency_component', models.IntegerField(default=0)),
                ('delay_component', models.IntegerField(default=0)),
                ('recent_behavior_component', models.IntegerField(default=0)),
                ('trend_component', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reliability_score', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('factors', models.JSONField(default=dict)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_health', to='businesses.business')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('factors', models.JSONField(default=dict)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collection_priority', to='customers.customer')),
            ],
        ),
    ]
